require("configuration.theme")
require("configuration.layouts")
require("configuration.mousebindings")
require("configuration.keybindings")
require("configuration.rules")
require("configuration.autofocus")
require("configuration.monitor")
require("configuration.music-notification")
