import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[window]
opacity = 0.9
decorations = "Full"

[font]
size = 12
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[mouse]
hide_when_typing = true
