[terminal.shell]
program = "/usr/bin/zsh"
args = ["--login"]

[window]
opacity = 0.9
decorations = "Full"

[font]
size = 12
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

[mouse]
hide_when_typing = true

[general]
import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[terminal]
