version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    powerline_symbol = ''
    leading_diamond = ''
    template = '{{.Icon}} '
    background = 'p:blue'
    foreground = 'p:wight'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .Path }}'
    background = 'p:mauve'
    foreground = 'p:text'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <dimgrey>{{ if gt .Behind 0 }}⭭{{end}}{{if gt .Ahead 0 }}⭫{{ end }}</>'
    background = 'p:lavender'
    foreground = 'p:text'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    powerline_symbol = ''
    leading_diamond = ''
    foreground = 'p:text'
    background = 'p:blue'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:green{{end}}",
    ]
    template = '❯'

[transient_prompt]
  background = 'transparent'
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:green{{end}}",
  ]
  template = '❯ '

[secondary_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:green{{end}}",
  ]
  background = 'transparent'
  template = '❯❯ '

[palette]
  rosewater = '#F5E0DC'
  pink = '#F5BDE6'
  mauve = '#CBA6F7'
  red = '#F38BA8'
  maroon = '#EBA0AC'
  green = '#A6E3A1'
  blue = '#8AADF4'
  lavender = '#B7BDF8'
  text = '#1E1E2E' # Base
  os = '#585B70'
  wight = '#FFFFFF'
