version = 3
final_space = true

[palette]
  blue = '#8AADF4'
  green = '#A6E3A1'
  lavender = '#B7BDF8'
  maroon = '#EBA0AC'
  mauve = '#CBA6F7'
  os = '#585B70'
  pink = '#F5BDE6'
  red = '#F38BA8'
  rosewater = '#F5E0DC'
  text = '#1E1E2E'
  wight = '#FFFFFF'

[secondary_prompt]
  template = '❯❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:green{{end}}']

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:green{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    template = '{{.Icon}} '
    foreground = 'p:wight'
    powerline_symbol = ''
    background = 'p:blue'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:mauve'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '....'
      home_icon = '~'
      style = 'full'

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <dimgrey>{{ if gt .Behind 0 }}⭭{{end}}{{if gt .Ahead 0 }}⭫{{ end }}</>'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:lavender'
    type = 'git'
    style = 'powerline'

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    leading_diamond = ''
    template = '{{ .FormattedMs }}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:blue'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:green{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
